apiVersion: apps.sealos.io/v1
kind: Application
metadata:
  name: growark-backend
  namespace: default
spec:
  displayName: "Growark Backend API"
  description: "星途成长方舟 - 实时三端同步系统后端"
  icon: "https://via.placeholder.com/48"

  template:
    metadata:
      labels:
        app: growark-backend
    spec:
      containers:
      - name: backend
        image: node:18-alpine
        workingDir: /app
        command:
          - /bin/sh
          - -c
          - |
            # 初始化代码
            cd /app && \
            npm install --production && \
            node server.js

        # 端口配置
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP

        # 环境变量
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3000"
        - name: DB_HOST
          value: "entr-postgresql.ns-ll4yxeb3.svc"
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: "postgres"
        - name: DB_USER
          value: "postgres"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password

        # 资源限制
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"

        # 健康检查
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 40
          periodSeconds: 10
          failureThreshold: 3

        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 2

  # 网络配置
  networking:
    - port: 3000
      name: http
      protocol: TCP

  # 副本数
  replicas: 3

  # 自动扩缩容
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 70
    targetMemoryUtilizationPercentage: 80

---
apiVersion: v1
kind: Service
metadata:
  name: growark-backend-svc
  namespace: default
  labels:
    app: growark-backend
spec:
  type: LoadBalancer
  selector:
    app: growark-backend
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  sessionAffinity: ClientIP
